# Generated by Django 5.1.3 on 2024-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingid', models.CharField(help_text='建筑物的标识符', max_length=24)),
                ('online_signatures', models.IntegerField(default=0, help_text='网签的数量')),
                ('subscriptions', models.IntegerField(default=0, help_text='认购的数量')),
                ('ready_houses', models.IntegerField(default=0, help_text='现房的数量')),
                ('future_houses', models.IntegerField(default=0, help_text='期房的数量')),
                ('mortgages', models.IntegerField(default=0, help_text='抵押的数量')),
                ('unsold_units', models.IntegerField(default=0, help_text='不可售的数量')),
                ('date_added', models.DateField(auto_now_add=True, help_text='记录创建的日期')),
            ],
        ),
    ]
