# Generated by Django 5.1.3 on 2024-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='project_name',
            field=models.CharField(default='', help_text='项目名称', max_length=100),
            preserve_default=False,
        ),
    ]
